---
- name: Test Kerberos WinRM
  hosts: all
  gather_facts: true

  tasks:
    - name: Show hostname
      ansible.windows.win_shell: hostname
      register: host

    - debug:
        var: host.stdout