---
- name: Show Windows connection vars
  hosts: all
  gather_facts: false

  tasks:
    - debug:
        msg:
          inventory_hostname: "{{ inventory_hostname }}"
          ansible_host: "{{ ansible_host | default('undefined') }}"
          ansible_user: "{{ ansible_user | default('undefined') }}"